name: forest_change_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip>=10.0
  - numpy==1.21.2
  - gdal==3.0.2
  - pandas==1.3.5
  - geopandas==0.6.1
  - matplotlib==3.5.0
  - rioxarray==0.9.1
  - click==7.1.2
  - shapely==1.7.1